// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"` // Using integer cents (e.g. 999 for $9.99) to prevent float inaccuracies.
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ReserveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItem) Reset() {
	*x = ReserveItem{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItem) ProtoMessage() {}

func (x *ReserveItem) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItem.ProtoReflect.Descriptor instead.
func (*ReserveItem) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReserveItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Serves as the idempotency key for this reservation
	Items         []*ReserveItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetItems() []*ReserveItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error details in case of failures (e.g. "Out of stock")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Maps back to the reservation to release
	Items         []*ReserveItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseStockRequest) GetItems() []*ReserveItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\x14ecommerce.catalog.v1\"\x86\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x12GetProductResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.ecommerce.catalog.v1.ProductR\aproduct\"Q\n" +
	"\x13ListProductsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"y\n" +
	"\x14ListProductsResponse\x129\n" +
	"\bproducts\x18\x01 \x03(\v2\x1d.ecommerce.catalog.v1.ProductR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"H\n" +
	"\vReserveItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"i\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.ecommerce.catalog.v1.ReserveItemR\x05items\"J\n" +
	"\x14ReserveStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"i\n" +
	"\x13ReleaseStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.ecommerce.catalog.v1.ReserveItemR\x05items\"0\n" +
	"\x14ReleaseStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa6\x03\n" +
	"\x0eCatalogService\x12_\n" +
	"\n" +
	"GetProduct\x12'.ecommerce.catalog.v1.GetProductRequest\x1a(.ecommerce.catalog.v1.GetProductResponse\x12e\n" +
	"\fListProducts\x12).ecommerce.catalog.v1.ListProductsRequest\x1a*.ecommerce.catalog.v1.ListProductsResponse\x12e\n" +
	"\fReserveStock\x12).ecommerce.catalog.v1.ReserveStockRequest\x1a*.ecommerce.catalog.v1.ReserveStockResponse\x12e\n" +
	"\fReleaseStock\x12).ecommerce.catalog.v1.ReleaseStockRequest\x1a*.ecommerce.catalog.v1.ReleaseStockResponseBFZDgithub.com/rajeev/ecommercesagapattern/shared/pb/catalogv1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*Product)(nil),              // 0: ecommerce.catalog.v1.Product
	(*GetProductRequest)(nil),    // 1: ecommerce.catalog.v1.GetProductRequest
	(*GetProductResponse)(nil),   // 2: ecommerce.catalog.v1.GetProductResponse
	(*ListProductsRequest)(nil),  // 3: ecommerce.catalog.v1.ListProductsRequest
	(*ListProductsResponse)(nil), // 4: ecommerce.catalog.v1.ListProductsResponse
	(*ReserveItem)(nil),          // 5: ecommerce.catalog.v1.ReserveItem
	(*ReserveStockRequest)(nil),  // 6: ecommerce.catalog.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil), // 7: ecommerce.catalog.v1.ReserveStockResponse
	(*ReleaseStockRequest)(nil),  // 8: ecommerce.catalog.v1.ReleaseStockRequest
	(*ReleaseStockResponse)(nil), // 9: ecommerce.catalog.v1.ReleaseStockResponse
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	0, // 0: ecommerce.catalog.v1.GetProductResponse.product:type_name -> ecommerce.catalog.v1.Product
	0, // 1: ecommerce.catalog.v1.ListProductsResponse.products:type_name -> ecommerce.catalog.v1.Product
	5, // 2: ecommerce.catalog.v1.ReserveStockRequest.items:type_name -> ecommerce.catalog.v1.ReserveItem
	5, // 3: ecommerce.catalog.v1.ReleaseStockRequest.items:type_name -> ecommerce.catalog.v1.ReserveItem
	1, // 4: ecommerce.catalog.v1.CatalogService.GetProduct:input_type -> ecommerce.catalog.v1.GetProductRequest
	3, // 5: ecommerce.catalog.v1.CatalogService.ListProducts:input_type -> ecommerce.catalog.v1.ListProductsRequest
	6, // 6: ecommerce.catalog.v1.CatalogService.ReserveStock:input_type -> ecommerce.catalog.v1.ReserveStockRequest
	8, // 7: ecommerce.catalog.v1.CatalogService.ReleaseStock:input_type -> ecommerce.catalog.v1.ReleaseStockRequest
	2, // 8: ecommerce.catalog.v1.CatalogService.GetProduct:output_type -> ecommerce.catalog.v1.GetProductResponse
	4, // 9: ecommerce.catalog.v1.CatalogService.ListProducts:output_type -> ecommerce.catalog.v1.ListProductsResponse
	7, // 10: ecommerce.catalog.v1.CatalogService.ReserveStock:output_type -> ecommerce.catalog.v1.ReserveStockResponse
	9, // 11: ecommerce.catalog.v1.CatalogService.ReleaseStock:output_type -> ecommerce.catalog.v1.ReleaseStockResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
